binday/server/models/base.py
from binday.server.factories.application import db


class Base(db.Model):
    __abstract__ = True

    date_created = db.Column(db.DateTime, default=db.func.now(), nullable=False)
    date_updated = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())

binday/server/models/user_config.py
from sqlalchemy.dialects.mysql import INTEGER

from binday.boards.board import BoardType
from binday.server.factories.application import db


class UserConfig(db.Model):
    __tablename__ = "user_config"

    pushbullet_api_key = db.Column(db.String(128))

    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False,  primary_key=True)
    user = db.relationship("User", foreign_keys=user_id)

    def __repr__(self):
        return f"<UserConfig>"

binday/server/views/auth.py
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    stream_with_context,
    url_for,
)
from flask_login import current_user, login_user, logout_user

from binday.server.factories.application import db
from binday.server.forms.auth import LoginForm, RegistrationForm
from binday.server.models.user import User

blueprint = Blueprint("auth", __name__)


@blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_obj = User.query.filter_by(email=form.email.data).first()

        if user_obj is None or not user_obj.check_password(form.password.data):
            flash("Invalid email or password.", "danger")

            return redirect(url_for("auth.login"))

        login_user(user_obj, remember=form.remember_me.data)

        return redirect(url_for("main.index"))

    return render_template("auth/login.html", form=form)


@blueprint.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@blueprint.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RegistrationForm()

    if form.validate_on_submit():
        user_obj = User(email=form.email.data)
        user_obj.set_password(form.password.data)

        db.session.add(user_obj)
        db.session.commit()

        flash("Congratulations, you are now a registered!", "success")

        return redirect(url_for("auth.login"))

    return render_template("auth/register.html", form=form)

binday/server/views/main.py
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    stream_with_context,
    url_for,
)
from flask_login import current_user, login_user, logout_user

from binday.binx.binx import BinActions, BinX
from binday.boards.board import Board, BoardType
from binday.boards.uno_r3 import UnoR3
from binday.server.factories.application import db
from binday.server.forms.main import UserConfigForm
from binday.server.models.bin_day import BinDay
from binday.server.models.my_bin import MyBin
from binday.server.models.user_config import UserConfig
from binday.utils.bin_utils import get_bin_level, get_bin_level_perc

blueprint = Blueprint("main", __name__)


@blueprint.route("/", methods=["GET"])
def index():
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login"))

    my_bin_objs = (
        MyBin.query.filter(MyBin.creator.has(id=current_user.id))
        .order_by("device_name")
        .all()
    )

    bin_sensor_data = {}
    prev_board = None

    for my_bin_obj in my_bin_objs:
        try:
            board = Board(device_name=my_bin_obj.device_name)

            if my_bin_obj.board_type == BoardType.UNO_R3:
                board = UnoR3(device_name=my_bin_obj.device_name)

            if prev_board != board:
                board.setup()
        except Exception as ex:
            flash(f"Bin {my_bin_obj.id} ({my_bin_obj.name}): {ex}", "warning")

            bin_sensor_data[my_bin_obj.id] = {
                "sonar_reading": None,
                "bin_level": None,
                "bin_level_perc": None,
                "led_status": None,
            }
        else:
            prev_board = board

            binx = BinX(my_bin_obj.name, my_bin_obj.sonar_id, my_bin_obj.led_id)
            bin_actions = BinActions(board, binx)

            sonar_reading = bin_actions.get_bin_sonar()
            led_status = bin_actions.get_bin_led_status()

            bin_sensor_data[my_bin_obj.id] = {
                "sonar_reading": sonar_reading,
                "bin_level": get_bin_level(my_bin_obj.height, sonar_reading),
                "bin_level_perc": get_bin_level_perc(my_bin_obj.height, sonar_reading),
                "led_status": led_status,
            }

    return render_template(
        "index.html", my_bins=my_bin_objs, bin_sensor_data=bin_sensor_data
    )


@blueprint.route("/user/settings", methods=["GET", "POST"])
def user_config():
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login"))

    user_cofig_obj = UserConfig.query.filter(
        UserConfig.user.has(id=current_user.id)
    ).first()

    form = UserConfigForm(obj=user_cofig_obj)

    if form.validate_on_submit():
        if user_cofig_obj:
            user_cofig_obj.pushbullet_api_key = form.pushbullet_api_key.data
            db.session.merge(user_cofig_obj)
        else:
            new_user_config = UserConfig(user=current_user)
            new_user_config.pushbullet_api_key = form.pushbullet_api_key.data
            db.session.add(new_user_config)

        db.session.commit()

        flash(f"User settings updated!", "success")

        return redirect(url_for("main.index"))

    return render_template("user_config.html", form=form)

binday/server/templates/base.html
{% extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en"{% endblock %}

{% block styles %}
{{super()}}
<link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">BinDay</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_anonymous %}
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                {% else %}
                <li><a href="{{ url_for('main.user_config') }}">Settings</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'message' %}
    <div class="alert alert-warning" role="alert">
        {% else %}
        <div class="alert alert-{{ category }}" role="alert">
            {% endif %}
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {# application content needs to be provided in the app_content block #}
    {% block app_content %}{% endblock %}
</div>
{% endblock %}

binday/server/templates/index.html
{% extends 'base.html' %}

{% block title %}BinDay{% endblock %}

{% block app_content %}
<table class="table">
    <caption>My bins</caption>
    <thead>
        <tr>
            <th>#</th>
            <th>Bin</th>
            <th>Level (cm)</th>
            <th>Volume (%)</th>
            <th>Collection on</th>
            <th>Actions</th>
        <tr>
    </thead>
    <tbody>
        {% for my_bin in my_bins %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                <div class="bin-color-box" style="background-color: {{ my_bin.color_hex }};"></div>
                {{ my_bin.name }} (ID: {{ my_bin.id }})
            </td>
            <td>{{ bin_sensor_data[my_bin.id].bin_level }}</td>
            <td>{{ bin_sensor_data[my_bin.id].bin_level_perc }}</td>
            <td>{{ my_bin.bin_day.day_index.value }} ({{ my_bin.bin_day.frequency.value }})</td>
            <td>
                <a href="bins/{{ my_bin.id }}" class="btn btn-info btn-sm" role="button">View</a>
                <a href="bins/{{ my_bin.id }}/edit" class="btn btn-secondary btn-sm" role="button">Edit</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<br />
<a href="bins/create" class="btn btn-primary" role="button">Add a bin</a>

{% endblock %}

binday/server/templates/user_config.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}User settings{% endblock %}

{% block app_content %}
<h1>User settings</h1>
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
<br>
{% endblock %}